# Generated by Django 3.1.2 on 2020-10-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebahoz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url_download', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'لینک دانلود',
                'verbose_name_plural': 'لینک های دانلود',
                'ordering': ('-created',),
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-created',), 'verbose_name': 'آموزش', 'verbose_name_plural': 'آموزش ها'},
        ),
        migrations.AddField(
            model_name='course',
            name='GB',
            field=models.CharField(max_length=250, null=True, verbose_name='حجم فایل ها'),
        ),
        migrations.AlterField(
            model_name='course',
            name='des',
            field=models.TextField(verbose_name='توضیح دربارە درس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(max_length=250, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=250, verbose_name='نام درس'),
        ),
        migrations.AddField(
            model_name='course',
            name='downloads',
            field=models.ManyToManyField(blank=True, related_name='downloads', to='ebahoz.Download'),
        ),
    ]
