# Generated by Django 3.1.2 on 2020-10-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebahoz', '0002_auto_20201016_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Free', 'free'), ('IS NOT FREE', 'is not free')], default='Free', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='GB',
            field=models.CharField(max_length=250, null=True, verbose_name='حجم درس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='downloads',
            field=models.ManyToManyField(blank=True, related_name='downloads', to='ebahoz.Download', verbose_name='لینک های دانلود'),
        ),
        migrations.AlterField(
            model_name='course',
            name='poster',
            field=models.ImageField(blank=True, upload_to='ebahoz/poster/', verbose_name='آپلود پوستر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='created', verbose_name='مقدار نمایشی در url'),
        ),
        migrations.AlterField(
            model_name='download',
            name='title',
            field=models.CharField(max_length=250, verbose_name='پارت'),
        ),
        migrations.AlterField(
            model_name='download',
            name='url_download',
            field=models.URLField(verbose_name='لینک دانلود'),
        ),
    ]
