# Generated by Django 3.1.2 on 2020-10-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebahoz', '0003_auto_20201016_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Free', 'free'), ('PRICE', 'price')], default='Free', max_length=50),
        ),
    ]
