# Generated by Django 3.1.2 on 2020-10-16 12:50

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ebahoz', '0004_auto_20201016_1139'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('free_courses', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Free', 'free'), ('PRICE', 'price')], default='Free', max_length=50, verbose_name='نوع آموزش'),
        ),
    ]
