# Generated by Django 3.0.8 on 2020-07-27 22:13

import account_k.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account_k', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_k',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='account_k',
            name='image',
            field=models.ImageField(upload_to=account_k.models.upload_image_path),
        ),
    ]
