# Generated by Django 3.0.8 on 2020-07-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_k', '0004_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_k',
            name='username',
            field=models.CharField(max_length=120),
        ),
    ]
