# Generated by Django 3.0.8 on 2020-07-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_k', '0005_auto_20200727_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_k',
            name='phone',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
