# Generated by Django 3.0.8 on 2020-07-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_k', '0006_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_k',
            name='ip_user',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
