# Generated by Django 3.0.8 on 2020-08-01 20:12

import account_k.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_k', '0007_account_ip_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account_k',
            options={'verbose_name': 'اطلاعات بیشتر کاربر', 'verbose_name_plural': 'اطلاعات بیشتر کاربران'},
        ),
        migrations.AlterField(
            model_name='account_k',
            name='image',
            field=models.ImageField(upload_to=account_k.models.upload_image_path,verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='account_k',
            name='ip_user',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ip کاربر'),
        ),
        migrations.AlterField(
            model_name='account_k',
            name='phone',
            field=models.CharField(blank=True, max_length=120, verbose_name='شمارە تلفن'),
        ),
        migrations.AlterField(
            model_name='account_k',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='account_k',
            name='username',
            field=models.CharField(max_length=120, verbose_name='نام کاربری'),
        ),
    ]
