# Generated by Django 3.1.2 on 2020-10-05 19:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_k', '0008_auto_20200801_2012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account_k',
            new_name='account',
        ),
    ]
