# Generated by Django 3.0.8 on 2020-07-29 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wrongword', '0002_wrong_word_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrong_word',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
