# Generated by Django 3.1.2 on 2020-10-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='Upload/image/profiles')),
                ('job', models.CharField(max_length=250)),
                ('telegram', models.URLField(default='t.me/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اطلاعات اعضای تیم',
                'ordering': ('-created',),
            },
        ),
    ]
