# Generated by Django 3.1.2 on 2020-10-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_k', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile_bio',
            options={'ordering': ('-created',), 'verbose_name': 'اطلاعات اعضای تیم', 'verbose_name_plural': 'اطلاعات اعضای تیم'},
        ),
    ]
