# Generated by Django 3.1.2 on 2020-10-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_k', '0002_auto_20201011_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_bio',
            name='des',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='profile_bio',
            name='image',
            field=models.ImageField(blank=True, upload_to='Upload/image/profiles', verbose_name='عکس پرۆفایل'),
        ),
        migrations.AlterField(
            model_name='profile_bio',
            name='job',
            field=models.CharField(max_length=250, verbose_name='جایگاە'),
        ),
        migrations.AlterField(
            model_name='profile_bio',
            name='name',
            field=models.CharField(max_length=250, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='profile_bio',
            name='telegram',
            field=models.URLField(default='t.me/', verbose_name='ایدی تلگرام'),
        ),
    ]
