# Generated by Django 3.0.8 on 2020-07-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kurdishdic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurdish', models.CharField(max_length=120)),
                ('persian', models.CharField(max_length=120)),
                ('word_id', models.CharField(max_length=120)),
                ('dic', models.CharField(max_length=120)),
                ('simple', models.TextField(blank=True)),
            ],
        ),
    ]
