# Generated by Django 3.0.8 on 2020-07-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurdishdic', '0002_auto_20200728_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurdishdic',
            name='kurdish',
        ),
    ]
