# Generated by Django 3.0.8 on 2020-07-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurdishdic', '0003_remove_kurdishdic_kurdish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurdishdic',
            old_name='simple',
            new_name='simple_kurmanci',
        ),
        migrations.AddField(
            model_name='kurdishdic',
            name='simple_sorani',
            field=models.TextField(blank=True),
        ),
    ]
