# Generated by Django 3.0.8 on 2020-07-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurdishdic', '0004_auto_20200728_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurdishdic',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
