# Generated by Django 3.0.8 on 2020-07-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurdishdic', '0005_kurdishdic_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurdishdic',
            name='kurmanci',
        ),
        migrations.RemoveField(
            model_name='kurdishdic',
            name='simple_kurmanci',
        ),
    ]
