# Generated by Django 3.0.8 on 2020-07-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurdishdic', '0006_auto_20200728_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurdishdic',
            name='simple_sorani',
            field=models.TextField(blank=True, default='بدون مثال'),
        ),
    ]
