# Generated by Django 3.0.8 on 2020-08-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurdishdic', '0007_auto_20200729_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurdishdic',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='kurdishdic',
            name='simple_sorani',
            field=models.TextField(blank=True, default='بدون مثال', null=True),
        ),
        migrations.AlterField(
            model_name='kurdishdic',
            name='word_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
