# Generated by Django 3.0.8 on 2020-08-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurdishdic', '0008_auto_20200801_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurdishdic',
            name='active',
        ),
    ]
