# Generated by Django 3.0.8 on 2020-08-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurdishdic', '0009_remove_kurdishdic_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurdishdic',
            name='word_id',
        ),
        migrations.AlterField(
            model_name='kurdishdic',
            name='persian',
            field=models.CharField(max_length=120, verbose_name='فارسی'),
        ),
        migrations.AlterField(
            model_name='kurdishdic',
            name='simple_sorani',
            field=models.TextField(blank=True, default='بدون مثال', null=True, verbose_name='مثال'),
        ),
        migrations.AlterField(
            model_name='kurdishdic',
            name='sorani',
            field=models.CharField(blank=True, max_length=120, verbose_name='سورانی'),
        ),
    ]
