# Generated by Django 3.0.8 on 2020-08-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurdishdic', '0010_auto_20200801_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kurdishdic',
            options={'verbose_name': 'کلمه', 'verbose_name_plural': 'کلمات'},
        ),
    ]
